#pragma once

#include <engine/core/Base/EchoConfig.h>
#include "engine/core/Base/EchoDef.h"

namespace Echo
{
	// ÉùÃ÷
	class Time;
	class TimeProfiler;
	class Vector2;
	class Vector3;
	class Vector4;
	class Matrix4;
	class Quaternion;
	class Triangle;
	class Circle;
	class Rect;
	class Sphere;
	class Plane;
	class Frustum;
	class Ray;
	class ParamSurface;
	class SimpleSpline;
	class LogManager;
	class Root;
	class ProjectSettings;
	class Color;
	class PixelBox;
	class GPUBuffer;
	class Shader;
	class ShaderProgram;
	class RenderState;
	class TextureRes;
	class MemoryManager;
	class TextureResManager;
	class RenderInput;
	class RenderView;
	class RenderTargetView;
	class DepthStencilView;
	struct Viewport;
	class FrameBuffer;
	class Renderer;
	class ManualRenderListener;
	class Renderable;
	class RenderQueue;
	class Bone;
	class Skeleton;
	class SkeletonManager;
	class Animation;
	class AnimState;
	class AnimKeyFrame;
	class AnimManager;
	class AnimBlender;
	class Mesh;
	class Camera;
	class CameraShadow;
	class DataStream;
	class ResourceManager;
	class IO;
	class Resource;
	class Archive;
	class TextureSet;
	class LightmapMgr;
	class LightmapRasterizer;
	class OpenMPTaskMgr;
	class Model;
	class ModelManager;
	class SkeletonManager;
	class AnimManager;
	class AnimSystemManager;
	class PhysicsManager;
	class FSAudioManager;
	class NetConnectionManager;
	class ScenarioManager;
	class ISkeletonController;
}

#include "engine/core/Util/StringUtil.h"
#include "engine/core/Util/AssertX.h"
#include "engine/core/Util/TimeProfiler.h"
#include "engine/core/Util/Exception.h"
#include "engine/core/Util/Log.h"
#include "engine/core/Util/LogManager.h"
#include "engine/core/main/OpenMPTaskMgr.h"
#include "engine/core/Thread/Threading.h"
#include "engine/core/Math/MathLib.h"
#include "engine/core/geom/GeomLib.h"
#include "engine/core/Util/Timer.h"
#include "engine/core/Math/MathLib.h"
#include "engine/core/io/DataStream.h"
#include "engine/core/io/IO.h"
#include "engine/core/Resource/ResourceManager.h"
#include "engine/core/Resource/Resource.h"
#include "engine/core/render/render/Color.h"
#include "engine/core/render/render/PixelFormat.h"
#include "engine/core/render/render/PixelConversions.h"
#include "Engine/core/camera/Camera.h"
#include "Engine/core/camera/CameraShadow.h"
#include "Engine/core/Render/TextureRes.h"
#include "Engine/core/Render/TextureResManager.h"