
add_library(Qt5::QGeoServiceProviderFactoryNokia MODULE IMPORTED)

_populate_Location_plugin_properties(QGeoServiceProviderFactoryNokia RELEASE "geoservices/libqtgeoservices_nokia.dylib")
_populate_Location_plugin_properties(QGeoServiceProviderFactoryNokia DEBUG "geoservices/libqtgeoservices_nokia.dylib")

list(APPEND Qt5Location_PLUGINS Qt5::QGeoServiceProviderFactoryNokia)
