/*=============================================================================
	MonteCarlo.h: Utilities for Monte Carlo integration.
	Copyright 1998-2013 Epic Games, Inc. All Rights Reserved.
=============================================================================*/

#pragma once

namespace Lightmass
{
	/** Generates valid X and Y axes of a coordinate system, given the Z axis. */
	void GenerateCoordinateSystem(const FVector4& ZAxis, FVector4& XAxis, FVector4& YAxis);
		
	/** Generates a pseudo-random unit vector, uniformly distributed over all directions. */
	FVector4 GetUnitVector(FRandomStream& RandomStream);

	/** Generates a pseudo-random position inside the unit sphere, uniformly distributed over the volume of the sphere. */
	FVector4 GetUnitPosition(FRandomStream& RandomStream);

	/** 
	 * Generates a pseudo-random unit vector in the Z > 0 hemisphere whose PDF == 1 / (2 * PI) in solid angles,
	 * Or sin(theta) / (2 * PI) in hemispherical coordinates, which is a uniform distribution over the area of the hemisphere.
	 */
	FVector4 GetUniformHemisphereVector(FRandomStream& RandomStream, FLOAT MaxTheta = (FLOAT)HALF_PI);

	/** 
	 * Generates a pseudo-random unit vector in the Z > 0 hemisphere whose PDF == cos(theta) / PI in solid angles,
	 * Which is sin(theta)cos(theta) / PI in hemispherical coordinates.
	 */
	FVector4 GetCosineHemisphereVector(FRandomStream& RandomStream, FLOAT MaxTheta = (FLOAT)HALF_PI);

	/** 
	 * Generates a pseudo-random unit vector in the Z > 0 hemisphere,
	 * Whose PDF == (SpecularPower + 1) / (2.0f * PI) * cos(Alpha) ^ SpecularPower in solid angles,
	 * Where Alpha is the angle between the perfect specular direction and the outgoing direction.
	 */
	FVector4 GetModifiedPhongSpecularVector(FRandomStream& RandomStream, const FVector4& TangentSpecularDirection, FLOAT SpecularPower);

	/** 
	 * Generates a pseudo-random position within a unit disk,
	 * Whose PDF == 1 / PI, which is a uniform distribution over the area of the disk.
	 */
	FVector2D GetUniformUnitDiskPosition(FRandomStream& RandomStream);

	/** 
	 * Generates a pseudo-random direction within a cone,
	 * Whose PDF == 1 / (2 * PI * (1 - CosMaxConeTheta)), which is a uniform distribution over the directions in the cone. 
	 */
	FVector4 UniformSampleCone(FRandomStream& RandomStream, FLOAT CosMaxConeTheta, const FVector4& XAxis, const FVector4& YAxis, const FVector4& ZAxis);

	/** Calculates the PDF for a sample generated by UniformSampleCone */
	FLOAT UniformConePDF(FLOAT CosMaxConeTheta);

	/** Generates unit length, stratified and uniformly distributed direction samples in a hemisphere. */
	void GenerateStratifiedUniformHemisphereSamples(INT NumThetaSteps, INT NumPhiSteps, FRandomStream& RandomStream, TArray<FVector4>& Samples);

	/** 
	 * Multiple importance sampling power heuristic of two functions with a power of two. 
	 * From Veach's PHD thesis titled "Robust Monte Carlo Methods for Light Transport Simulation", page 273.
	 */
	FLOAT PowerHeuristic(INT NumF, FLOAT fPDF, INT NumG, FLOAT gPDF);

	/** Calculates the step 1D cumulative distribution function for the given unnormalized probability distribution function. */
	void CalculateStep1dCDF(const TArray<FLOAT>& PDF, TArray<FLOAT>& CDF, FLOAT& UnnormalizedIntegral);

	/** Generates a Sample from the given step 1D probability distribution function. */
	void Sample1dCDF(const TArray<FLOAT>& PDFArray, const TArray<FLOAT>& CDFArray, FLOAT UnnormalizedIntegral, FRandomStream& RandomStream, FLOAT& PDF, FLOAT& Sample);

}
